on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run action
    steps:
      - name: Run action
        id: action
        uses: KusionStack/kusion-actions@main
        with:
          subcommand: "version"